[package]
name = "ada-gps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
ascii = { version = "1.0.0", default-features = false }
defmt = "0.3.0"
nmea-parser = "0.9.0"
heapless = "0.7.9"
